runtime: nodejs
env: flex

env_variables:
  # --REQUIRED--
  DATABASE_URI: mongodb://heroku_ms8z97z4:1t8qv73i2j7hsdb6nb7ac5lsd4@ds231987.mlab.com:31987/heroku_ms8z97z4
  APP_ID: mole-app-server
  MASTER_KEY: Robbie1997
  CLIENT_KEY: qwerty
  SERVER_URL: https://mole-app-server.herokuapp.com/parse
  # --OPTIONAL--
  # FILE_KEY: <your-file-key>
  # PARSE_MOUNT: /parse
  # CLOUD_CODE_MAIN:  
